[package]
name = "minifb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.24"
rand = "0.8.5"
noise = { version = "0.8.2", features = ["images"] }
fontdue = "0.7.3"
crossbeam = "0.8.2"